language: go
go:
    - 1.14.x

dist: bionic

sudo: required

env:
    global:
        - GO111MODULE=on
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=localhost
        - POSTGRES_DB=chat-app
        - POSTGRES_USER=chat
        - POSTGRES_PASSWORD=postgres
        - SESSION_SECRET=sessionsecret
        - KEYSPACE=chatserver
        # - PG_PORT=5432
    

services:
    - postgresql
    - cassandra

addons:
    postgresql: "10"
    
before_script:
    - nodetool status
    - cqlsh -e "CREATE KEYSPACE IF NOT EXISTS chatserver WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};"
    - psql -c 'CREATE ROLE chat WITH SUPERUSER CREATEDB LOGIN;' -U postgres
    - psql -c 'CREATE DATABASE chat;' -U postgres 
    - psql -c 'CREATE DATABASE "chat-app";' -U chat 