language: go
go:
    - 1.14.x

dist: bionic

sudo: required

env:
    global:
        - GO111MODULE=on
        - DB_PORT=5432
        - DB_HOST=localhost
        - POSTGRES_DB=chat-app
        - POSTGRES_USER=chat
        - POSTGRES_PASSWORD=postgres
        - SESSION_SECRET=sessionsecret
        - KEYSPACE=chatserver
        # - PG_PORT=5432
    

services:
    - postgresql
    - docker

addons:
    postgresql: "10"
    
before_script:
    # - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5e08fbd8b5d6ec9c
    # - sudo curl -o /etc/apt/sources.list.d/scylla.list -L http://repositories.scylladb.com/scylla/repo/a6a13203-ab85-4771-a1d6-5edb5fecaf69/ubuntu/scylladb-4.1-bionic.list
    # - sudo apt-get update
    # - sudo apt-get install scylla-jmx
    # - sudo apt-get -y install scylla
    # - sudo apt-get update
    # - sudo apt-get install -y openjdk-8-jre-headless
    # - sudo update-java-alternatives --jre-headless -s java-1.8.0-openjdk-amd64
    - docker run --name some-scylla --hostname some-scylla -d scylladb/scylla --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' some-scylla)"
    - docker exec -it some-scylla nodetool status
    # - sudo scylla_setup --no-memory-setup --no-kernel-check --no-bootparam-setup --no-coredump-setup --no-ntp-setup --no-raid-setup --no-sysconfig-setup --no-io-setup --no-version-check --no-cpuscaling-setup --no-fstrim-setup
    # - sudo scylla_dev_mode_setup --developer-mode 1
    # - sudo /opt/scylladb/bin/scylla --memory 2G --smp 2 --overprovisioned
    # - sleep 15
    # - nodetool status
    - psql -c 'CREATE ROLE chat WITH SUPERUSER CREATEDB LOGIN;' -U postgres
    - psql -c 'CREATE DATABASE chat;' -U postgres 
    - psql -c 'CREATE DATABASE "chat-app";' -U chat 