language: go
go:
    - 1.14.x
env:
    global:
        - GO111MODULE=on
        - DB_PORT=5432
        - DB_HOST=localhost
        - POSTGRES_DB=chat-app
        - POSTGRES_USER=chat
        - POSTGRES_PASSWORD=postgres
        - SESSION_SECRET=sessionsecret
        - KEYSPACE=chatserve
    

services:
    - postgresql

addons:
    postgresql: "10.12"
    
before_script:
    - psql -c 'create database test_ci;' -U postgres