language: go
go:
    - 1.14.x

dist: bionic

env:
    global:
        - GO111MODULE=on
        - DB_PORT=5432
        - DB_HOST=localhost
        - POSTGRES_DB=chat-app
        - POSTGRES_USER=chat
        - POSTGRES_PASSWORD=postgres
        - SESSION_SECRET=sessionsecret
        - KEYSPACE=chatserver
        # - PG_PORT=5432
    

services:
    - postgresql

addons:
    postgresql: "10"
    
before_script:
    - psql -c 'CREATE ROLE chat WITH SUPERUSER CREATEDB LOGIN;' -U postgres
    - psql -c 'CREATE DATABASE;' -U chat
    - psql -c 'CREATE DATABASE test_ci;' -U chat 