language: go
go:
    - 1.14.x
env:
    global:
        - GO111MODULE=on
        - DB_PORT=5432
        - DB_HOST=localhost
        - POSTGRES_DB=chat-app
        - POSTGRES_USER=chat
        - POSTGRES_PASSWORD=postgres
        - SESSION_SECRET=sessionsecret
        - KEYSPACE=chatserver
        # - PG_PORT=5432
    

services:
    - postgresql

addons:
    postgresql: "10"
    
before_script:
    - psql -c 'create role chat;'
    - psql -c 'create database test_ci;' -U chat 