receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint:
  #       # endpoint: "0.0.0.0:14268"
  otlp:
    protocols:
      grpc: # on port 55680
      http: # on port 55681

processors:
  batch:
# attributes:
#   actions:
#     - key: user
#       action: delete

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"
  jaeger:
    es:
      server-urls: http://localhost:9200
      num-replicas: 2

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      # receivers: [jaeger, otlp]
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, jaeger]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
