receivers:
  # jaeger:
  #   protocols:
  #     thrift_http:
  #       endpoint: "0.0.0.0:9000"
  otlp:
    protocols:
      grpc: # on port 55680
      http: # on port 55681

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      # receivers: [jaeger, otlp]
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
