# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, ci-testing ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build chat app
      run: go build main.go 

  test:
    runs-on: ubuntu-18.04
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat-app 
      DB_PORT: 5432
      DB_HOST: localhost
      DB_PASSWORD: postgres
      SESSION_SECRET: sessionsecret
      KEYSPACE: chatserver
    services:
      postgres:
        image: postgres:10.12
        ports: 
          - 5432:5432
        options: >- 
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    needs: [build]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      - name: testing code
        run: go test ./...

