name: Test

on: 
    push:
        branches: [ travisCI ]
        # branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: Test Code
        runs-on: ubuntu-18.04
        # container: ubuntu:18.04

        services:
            postgres:
                image: postgres:10.12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: chat-app 
                    POSTGRES_PORT: 5432
                    POSTGRES_HOST: postgres 
                    SESSION_SECRET: sessionsecret
                    #   KEYSPACE: chatserver
                ports: 
                    - 5432:5432
                options: >- 
                    --health-cmd pg_isready 
                    --health-interval 10s 
                    --health-timeout 5s 
                    --health-retries 5

            cassandra:
                image: cassandra
                ports:
                    - 7199:7199
                options: >-
                    --health-cmd "nodetool status"
                    --health-interval 10s 
                    --health-timeout 5s 
                    --health-retries 5

        steps:
            - name: Check out respository Code
              uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.14.7
            - name: testing code
              run: |
                psql -c 'CREATE ROLE chat WITH SUPERUSER CREATEDB LOGIN;' -U postgres -h localhost -p 5432 -w
                psql -c 'CREATE DATABASE chat;' -U postgres 
                psql -c 'CREATE DATABASE "chat-app";' -U chat 
                go test ./...
              env:
                POSTGRES_USER: chat
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: chat-app 
                POSTGRES_PORT: 5432
                POSTGRES_HOST: localhost 
                SESSION_SECRET: sessionsecret
                PGPASSWORD: postgres
