name: Test

on: 
    push:
        branches: [ travisCI ]
        # branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: Test Code
        runs-on: ubuntu-18.04
        # container: ubuntu:18.04

        services:
            postgres:
                image: postgres:10.12
                ports: 
                    - 5432:5432
                env:
                    POSTGRES_PASSWORD: postgres
                options: >- 
                    --health-cmd pg_isready 
                    --health-interval 10s 
                    --health-timeout 5s 
                    --health-retries 5

            cassandra:
                image: cassandra
                ports:
                    - 7199:7199
                    - 9042:9042
                options: >-
                    --health-cmd "nodetool status"
                    --health-interval 10s 
                    --health-timeout 5s 
                    --health-retries 5

        steps:
            - name: Check out respository Code
              uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.14.7
            - name: testing code
              run: |
                psql -c "CREATE ROLE chat WITH SUPERUSER CREATEDB LOGIN PASSWORD 'postgres';" -U postgres -h localhost -p 5432 -w
                psql -c 'CREATE DATABASE chat;' -U postgres -h localhost -p 5432 -w
                psql -c 'CREATE DATABASE "chat-app";' -U chat -h localhost -p 5432 -w
                go test ./...
              env:
                POSTGRES_USER: chat
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: chat-app 
                POSTGRES_PORT: 5432
                POSTGRES_HOST: localhost 
                SESSION_SECRET: sessionsecret
                PGPASSWORD: postgres
                KEYSPACE: chatserver
            # - name: create chat role
            #   env:
            #     PGPASSWORD: postgres
            #   run: psql -c "CREATE ROLE chat WITH SUPERUSER CREATEDB LOGIN PASSWORD 'postgres';" -U postgres -h localhost -p 5432 -w
            # - name: create chat database 
            #   env:
            #     PGPASSWORD: postgres
            #   run: psql -c 'CREATE DATABASE chat;' -U postgres -h localhost -p 5432 -w
            # - name: create chat-app database 
            #   env:
            #     PGPASSWORD: postgres
            #   run: psql -c 'CREATE DATABASE "chat-app";' -U chat -h localhost -p 5432 -w

                # env:
                #     POSTGRES_USER: postgres
                #     POSTGRES_PASSWORD: postgres
                #     POSTGRES_DB: chat-app 
                #     POSTGRES_PORT: 5432
                #     POSTGRES_HOST: postgres 
                #     SESSION_SECRET: sessionsecret
                    #   KEYSPACE: chatserver